### PR TITLE
Update generate-alertmanager-config-secret.sh

### PR DESCRIPTION
**Pull request by vpistis**
fix AlertManager config map generation for macos when base64 command return multiline string

### CODE REVIEW

**Comment by camilb** [comment]
Hi @vpistis, first of all, thanks for your contribution. In my experience, `base64` installed from homebrew it allows passing the `--wrap` or `--break`  flag, but doesn't work properly. Do you have it installed from another source? Which version?  
Second, the IF statement you add it breaks the current behaviour and I think it should be something like: 
```bash
# For MacOS that support --wrap=0 base64 return a multiline string
if [[ $(cat ../assets/alertmanager/alertmanager.yaml | $b64 | wc -l) > 1 ]]; then
    b64="base64 --wrap=0"
fi
```

**Comment by vpistis** [comment]
Hi @camilb , thanks for you suggestion, I can apply into source asap.
My base64 version is: `base64 (GNU coreutils) 8.29` and is the default standard fomr my macos High Siera 10.13.2 (17C205).

Thanks a lot for this project

**Comment by MansoorMajeed** [comment]
Oh, I didn't see this PR. I have made another fix here : https://github.com/camilb/prometheus-kubernetes/pull/65/files

**Comment by camilb** [comment]
@vpistis are you using `base64` installed by `brew install base64`  or `gbase64` installed by `brew install coreutils`? I think the brew version doesn't work correctly even if not showing an error. You can pass any flag, like `--something=0` and will not show anything. Discussing this issue here: https://github.com/camilb/prometheus-kubernetes/pull/65#issuecomment-363496436

**Comment by vpistis** [comment]
Hi @camilb , sorry for the lag, but I was out last week.
I have the GNU version installed whit `brew install coreutils`  and I have renamed the binary from `gbase64` to `base64` ... it's a brew option to use GNU instead of macos versions  :) 

If this PR it's so problematic you can reject it and waiting for further tests :)

**Comment by camilb** [comment]
@vpistis Please let me know if the solution in #71 works for you. Thanks!

**Comment by vpistis** [comment]
@camilb perfect, it works! :)
Thank you so much!

**Pull request closed without merging**
