### PR TITLE
update default to latest stable version

### PR DESCRIPTION
**Pull request by ArchiFleKs**

### CODE REVIEW

**Comment by drubin** [comment]
Does this not require a bunch of rbac rules? I tried this and it didn't seem to work out the box. (Or is the only change #102)

**Comment by ArchiFleKs** [comment]
@drubin Hi, I tried with the version from this PR and the only issue I had was with the RBAC fixed in the #102

**Comment by drubin** [comment]
@ArchiFleKs Maybe we should combine these two PR's then if they are actually linked? 

I tried them and I was missing all my alerts/rules, I can maybe try upgrading to these versions.

What is the recommended approach for "upgrading" components with this tool? just edit the numbers and deploy again? (This part feels a little clunky right now)

**Comment by camilb** [comment]
@ArchiFleKs @drubin Will merge this and push a fix for alert rules later

**Comment by camilb** [comment]
@ArchiFleKs @drubin  Fixed rules in #108

**Pull request merged**
